### PR TITLE
Feat/locust grpc

### PR DESCRIPTION
**Pull request by sayakpaul**
@deep-diver currently, the load test runs into:

Screenshot 2022-04-02 at 10 54 26 AM

I have ensured https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/feat/locust-grpc/locust/grpc/locustfile.py#L49 returns the correct output. But after a few requests, I run into the above problem. 

Also, I should mention that the gRPC client currently does not take care of image resizing which makes it a bit less comparable to the REST client which handles preprocessing as well postprocessing.

### CODE REVIEW

**Comment by deep-diver** [comment]
@sayakpaul 

can you share the computer spec that you used for gRPC client? It looks like the client side resources have been exhausted([Ref](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)).

> Also, I should mention that the gRPC client currently does not take care of image resizing which makes it a bit less comparable to the REST client which handles preprocessing as well postprocessing.

About this, I am not sure but isn't the `preprocessing` handled on server side? like using `keras.application`'s embedded preprocessing capability for a specific model. For the RestAPI test with Locust, I didn't use any preprocessing codes either.

**Comment by sayakpaul** [comment]
I used an N1 highmem instance: 16 vCPUs, 104 GB RAM. 

> About this, I am not sure but isn't the preprocessing handled on server side? like using keras.application's embedded preprocessing capability for a specific model. For the RestAPI test with Locust, I didn't use any preprocessing codes either.

You're right. But there's still a resizing op in the FastAPI client:

https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/main/api/utils/utils.py#L14

This is not the case for the gRPC client i.e., we are doing the resizing from the client side. 

There's also a postprocessing layer:

https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/main/api/utils/utils.py#L29

**Comment by deep-diver** [comment]
@sayakpaul

I see. For the Rest Client to test out Locust load test, I haven't included Preprocessing codes. So I assume that makes both situation fair enough for load testing purpose.

Also postprocessing is the client side job which means it has nothing to do with load testing I think. We can simply ignore postprocessing for this purpose I guess.

Can you access more detailed message why we get exhausted error?

**Comment by sayakpaul** [comment]
> I see. For the Rest Client to test out Locust load test, I haven't included Preprocessing codes. So I assume that makes both situation fair enough for load testing purpose.

> Also postprocessing is the client side job which means it has nothing to do with load testing I think. We can simply ignore postprocessing for this purpose I guess.

Agreed. But how come the model was able to predict on an image that is not 224x224 resolution? This is weird.

> Can you access more detailed message why we get exhausted error?

Will do.

**Comment by sayakpaul** [comment]
@deep-diver repining for this one:

> Agreed. But how come the model was able to predict on an image that is not 224x224 resolution? This is weird.

**Comment by sayakpaul** [comment]
@deep-diver I did this (following [this](https://github.com/grpc/grpc/blob/v1.45.x/include/grpc/impl/codegen/grpc_types.h#L156)):

```
self.channel = grpc.insecure_channel("34.135.245.34:8500", options=(("grpc.max_send_message_length", -1), ))
```

But we still have:

image

This time I used an instance containing 96 vCPUs, and 624 GBs of RAM.

**Comment by deep-diver** [comment]
> @deep-diver repining for this one:
> 
> > Agreed. But how come the model was able to predict on an image that is not 224x224 resolution? This is weird.

looks like the server side handles this issue ([Ref](https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/322f4b39fb0c7849b67f59883b6d16d33cda8741/api/main.py#L43)).

`prepare_image` function is called when someone post a message with bytes of file

**Comment by sayakpaul** [comment]
Yes exactly. If you see there it also has post-processing code (with decode_predictions()).

**Comment by deep-diver** [comment]
> options=(("grpc.max_send_message_length", -1), )

so this means set `max_send_message_length` to max?

**Comment by deep-diver** [comment]
> Yes exactly. If you see there it also has post-processing code (with decode_predictions()).

then it makes sense that the client works without any resizing

**Comment by deep-diver** [comment]
even if the request fails, it should stop the program I guess like by including an exception handling.

**Comment by sayakpaul** [comment]
> > Yes exactly. If you see there it also has post-processing code (with decode_predictions()).
> 
> then it makes sense that the client works without any resizing

It does but the comparison becomes a little unfair that way, no? But I think it's okay to ignore it for the time being.

**Comment by deep-diver** [comment]
> It does but the comparison becomes a little unfair that way, no? But I think it's okay to ignore it for the time being.

Oh Now I understand what you mean. The reason it worked on the notebook is the dummy data is initialized with the size of (224, 224). I guess that is why. I should modify the image by including a sort of resizing layer like [this](https://keras.io/api/layers/preprocessing_layers/image_preprocessing/resizing/). WDYT?

**Comment by deep-diver** [comment]
This is a good point that TF Serving is not flexible since it only allows us to include custom models. We can not include any further custom logics.

**Comment by deep-diver** [comment]
hmmm... but it is weird that RestAPI test did work somehow.... I need to make sure it works correctly as well. Please wait until tomorrow to reflect those changes.

**Comment by sayakpaul** [comment]
> This is a good point that TF Serving is not flexible since it only allows us to include custom models. We can not include any further custom logics.

Maybe we could add a custom signature to the model call so that it does a similar kind of preprocessing. If you remember the `_model_exporter()` utility from our notebook: https://github.com/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/notebooks/Custom_Model_TFX.ipynb.

**Comment by sayakpaul** [comment]
Closing this since we have moved TF Serving Locust testing to a separate repository:

https://github.com/deep-diver/ml-deployment-k8s-tfserving

**Pull request closed without merging**
